---
- name: Enable cgroup features for docker (Debian)
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: True
    regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory'
    state: present
  register: cgroups
  when: 
    - ansible_distribution == 'Debian'

- name: Enable cgroup features for docker (Ubuntu)
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: True
    regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory'
    state: present
  register: cgroups
  when: 
    - ansible_distribution == 'Ubuntu'

- name: Reboot and wait for connection
  reboot:
    reboot_timeout: 300
  when: cgroups.changed
