---
- name: Install python
  apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
    state: present

- name: Install python packages
  pip:
    name:
      - requests
      - openshift
      - 'urllib3<1.25'
    state: present
    executable: pip3
